add: other queries for shared snapshots
cloudquery-policies/aws pull request #107
Opened 2022-02-03 15:50 UTC by michelvocks

Closes https://github.com/cloudquery-policies/aws/issues/106

I wasn't sure if it makes more sense to add a new "other" folder below every sub-api-endpoint instead of the top level. Happy to change that if necessary.

2022-02-03 15:57 UTC, yevgenypats requested changes
I think the right structure here should be all the `queries` and `queries` and have `other.hcl` and add it to https://github.com/cloudquery-policies/aws/blob/main/policy.hcl . This way we keep the same convention + it will get indexed in hub.cloudquery.io

2022-02-03 15:58 UTC, yevgenypats commented
Another point: without it being in a subpolicy a user can't run it in the command line via `policy` command

2022-02-03 16:47 UTC, yevgenypats approved these changes
LGTM. just need to fix the title for the CI to pass

2022-02-07 08:19 UTC, roneli commented
would add the query in #107 and add user as contributor to this PR.

2022-02-09 15:17 UTC, yevgenypats requested changes
Had one comment on the linter. also looks like the second test it failing for some reason.

2022-02-09 15:17 UTC, yevgenypats commented on .github/workflows/lint.yml
> -      - name: Set up Go 1.x
maybe keep the hcl formatter ?

2022-06-27 07:50 UTC, erezrokah commented
Going to close this as stale. If I got this wrong please let me know and I'll re-open

2022-06-27 07:50 UTC, closed without merging