Foundational security ec2
cloudquery-policies/aws pull request #37
Opened 2021-11-26 17:27 UTC by amanenk

almost all the controls of ec2 section

2021-11-29 17:02 UTC, amanenk commented on queries/ec2/stopped_more_thant_30_days_ago_instances.sql
> +  AND NOW() - TO_TIMESTAMP(SUBSTRING(state_transition_reason FROM '\(([^\)]+)'), 'yyyy-MM-dd HH:mi:ss') >
It is a good idea. 
I agree that the solution is not neat but the only way to get timestamp. The only source of info about stop is state transition reason with next context `User initiated (2021-11-26 11:33:00 GMT)`
Also it could not work is there can be some other state transition after instance stop.
There also cloudtrail for this but we don't have events resource. we can try to add an instance relation tat loads a few last cloudtrail events to analyze instance better.
@roneli what do you think?

2021-11-30 17:09 UTC, bbernays requested changes

2021-11-30 17:09 UTC, bbernays commented on queries/ec2/aws_security_group_ingress_rules.sql
> +                               p.from_port,
This is a great view, we should update existing queries (like `no_broad_public_ingress_on_port_22.sql`) to use it

2021-12-01 18:12 UTC, bbernays commented on queries/ec2/aws_security_group_ingress_rules.sql
> +                               sg.group_name,
Can you add ARN to the view? maybe instead of `account_id`, `region` and `group_name`?

2021-12-01 18:31 UTC, bbernays approved these changes
LGTM, The only nitpick is you might want to replace `account_id`, `region`,`group_name` and `id` with `arn` as that is how developers know how to reference aws resources

2021-12-02 15:15 UTC, merged

2021-12-02 15:54 UTC, amanenk commented on queries/ec2/stopped_more_thant_30_days_ago_instances.sql
> +  AND NOW() - TO_TIMESTAMP(SUBSTRING(state_transition_reason FROM '\(([^\)]+)'), 'yyyy-MM-dd HH:mi:ss') >
I have created a pr(cloudquery/cq-provider-aws#325) that adds `transition_reason_time` column to ec2_instances.