FSBP: Implement SSM.4 check
cloudquery-policies/aws pull request #42
Opened 2021-11-29 12:39 UTC by irmatov

2021-11-29 15:57 UTC, yevgenypats approved these changes
lgtm. I'll let @bbernays take a second look.

2021-11-29 16:10 UTC, bbernays commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
Why are we checking the owner?

2021-11-30 07:41 UTC, irmatov commented on queries/ssm/documents_should_not_be_public.sql
> +WHERE 'all' = ANY(account_ids)
No, that doesn't work, unfortunately. That was my first attempt, too.

2021-11-30 07:45 UTC, irmatov commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
There are a lot of pre-made SSM documents, mostly by Amazon itself, around ~400 per region. We don't need them and I think they are not interesting to have in the database, so in the associated PR that fetches them (https://github.com/cloudquery/cq-provider-aws/pull/307) we fetch only documents that we have created ourselves (https://github.com/cloudquery/cq-provider-aws/pull/307/files#diff-0dbada14fb1b0c0b6ddd15cb80978347ffcb67c2fe45f56f2e6917b82692720eR213).

So on the policy side we need the same. Either we can cheat a bit and assume that table contains only our documents and not check the owner. In the case we would later retrieve *all* documents we would need to update this query, so I decided to just check the owner right away.

2021-12-01 17:38 UTC, bbernays commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
That makes sense! Can we instead exclude the AWS policies? I don't think it is reasonable to assume that CQ will have access to every single account in a customers organization.

2021-12-01 17:38 UTC, bbernays requested changes
Left a comment

2021-12-03 14:30 UTC, irmatov commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
Really not sure what to do.

Only filtering out Amazon on the policy side may not help - I think there are at least 2-3 more "vendors" of those SSM docs.

Also, excluding "known" third party public SSM docs on the policy side assumes we fetch all the docs - this will require changes to the resource fetch to collect *all* the documents.

2021-12-03 14:31 UTC, irmatov commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
@roneli @yevgenypats any thoughts on this?

2021-12-06 10:23 UTC, irmatov commented on queries/ssm/documents_should_not_be_public.sql
> +  AND owner IN (SELECT account_id FROM aws_accounts)
Giving this some more thought it seems to me that the proposed is the best we can do at the moment.

2021-12-09 10:59 UTC, merged