Aws foundational/waf wafv2
cloudquery-policies/aws pull request #50
Opened 2021-11-30 13:58 UTC by zagronitay

2021-11-30 21:14 UTC, disq requested changes

2021-11-30 21:14 UTC, disq commented on queries/wafv2/wafv2_web_acl_logging_should_be_enabled.sql
> +   OR logging_configuration = '{}';
```suggestion
   OR logging_configuration = '{}'
```

2021-12-01 18:23 UTC, bbernays requested changes

2021-12-01 18:23 UTC, bbernays commented on queries/wafv2/wafv2_web_acl_logging_should_be_enabled.sql
> +   OR logging_configuration = '{}';
What happens if logging is configured and then disabled? I know other services don't set the entire object to null/ empty, they just set the fields in the object to `NULL` or empty

2021-12-13 10:02 UTC, disq approved these changes
@zagronitay is there a manual test case about what @bbernays described? Can you check if configuring and then disabling logging results in an empty logging configuration, or would it create a `"some_key_disabled":true` (or the opposite) entry?

2021-12-20 12:38 UTC, disq approved these changes

2021-12-20 13:43 UTC, bbernays approved these changes
LGTM

2021-12-24 15:56 UTC, merged