Foundational Security: ELB
cloudquery-policies/aws pull request #51
Opened 2021-11-30 14:28 UTC by disq

2021-11-30 16:44 UTC, yevgenypats requested changes
better to use `is not true` or `is distinct from` for non-boolean. There was a slack discussion around it but basically if you have null values it will fail:

```
postgres=# select 1 where null != true;
 ?column? 
----------
(0 rows)
```

2021-11-30 16:44 UTC, yevgenypats commented on queries/elbv2/alb_drop_http_headers.sql
> +where lb.type='application' AND a.routing_http_drop_invalid_header_fields != true;
better to use `is not true`

2021-11-30 16:44 UTC, yevgenypats commented on queries/elbv2/alb_deletion_protection_enabled.sql
> +where lb.type='application' AND a.deletion_protection != true;
better to use `is not true`

2021-11-30 16:54 UTC, yevgenypats approved these changes

2021-12-01 17:45 UTC, bbernays commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
Do we need to break elbv2 and elbv1 into different folders? It seems weird for some queries like this one that check both

2021-12-01 17:55 UTC, disq commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
yeah, I don't know, I kind of agree. just move all to `elb/`?

2021-12-01 17:56 UTC, bbernays commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
I think that is a good idea

2021-12-01 18:14 UTC, disq commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
then if something just applies to the classic load balancer we can prefix that file with `elc`?

2021-12-01 18:55 UTC, disq commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
@yevgenypats what do you think?

2021-12-01 21:14 UTC, yevgenypats commented on foundational_security/policy.hcl
> +            query = file("queries/elbv2/alb_logging_enabled.sql")
yeah sounds good. let's do it.

2021-12-02 10:48 UTC, spangenberg approved these changes
LGTM

2021-12-02 15:19 UTC, merged