added ecs checks to foundations policy
cloudquery-policies/aws pull request #53
Opened 2021-11-30 16:02 UTC by amanenk

2021-12-01 17:35 UTC, disq requested changes

2021-12-01 17:35 UTC, disq commented on queries/ecs/task-definitions-secure-networking.sql
> +  AND (cd.privileged IS DISTINCT FROM TRUE OR cd."user" = 'root');
> This control checks whether an active Amazon ECS task definition that has host networking mode also has privileged or user container definitions. The control fails for task definitions that have host network mode and container definitions where privileged=false or is empty and user=root or is empty.

"user=root" is checked, but not the "is empty"

2021-12-01 17:48 UTC, bbernays commented on queries/ecs/task-definitions-secure-networking.sql
> +  AND (cd.privileged IS DISTINCT FROM TRUE OR cd."user" = 'root');
Won't `IS DISTINCT FROM TRUE` find all values that are not True (so null or false)?

2021-12-01 17:48 UTC, bbernays approved these changes
LGTM

2021-12-01 17:54 UTC, disq commented on queries/ecs/task-definitions-secure-networking.sql
> +  AND (cd.privileged IS DISTINCT FROM TRUE OR cd."user" = 'root');
> The control fails for task definitions that have host network mode and container definitions where privileged=false or is empty and user=root or is empty.

The control fails for :
 -> task definitions have host network mode
AND
 -> container definitions where privileged=false or is empty (this one is covered by `IS DISTINCT FROM TRUE`)
AND
 -> user=root or is empty (so I think a `cd."user" is null` needs to be added?)

at least that's how I parse that complex definition...

2021-12-01 18:34 UTC, disq requested changes
Another nit sorry didn't notice earlier: Filenames in queries/ should be separated with underscore and not `-`, as that's the way it's been done previously...

`ecs-services-with-public-ips.sql` => `ecs_services_with_public_ips.sql`
`task-definitions-secure-networking.sql` => `task_definitions_secure_networking.sql`

2021-12-02 09:31 UTC, disq approved these changes

2021-12-02 10:47 UTC, spangenberg approved these changes
LGTM

2021-12-02 15:20 UTC, merged