Add AWS Foundation Security for KMS
cloudquery-policies/aws pull request #60
Opened 2021-12-02 13:03 UTC by spangenberg

2021-12-02 17:27 UTC, bbernays requested changes
Overall looks good. just a couple of small things

2021-12-02 17:27 UTC, bbernays commented on queries/kms/inline_policy_blocked_kms_actions.sql
> +where arn not like '%service-role/%'
nit: can we make this `arn:aws:iam::%:role/aws-service-role/%` instead as the existing pattern can match with something like:

`arn:aws:iam::0123456789:role/test/pathat/user-aws-service-role/session`

2021-12-02 17:27 UTC, bbernays commented on queries/kms/inline_policy_blocked_kms_actions.sql
> +              'kms:reencryptfrom'] )
Is there some way we could simplify or remove this nearly duplicated query? Maybe make a view?

2021-12-03 09:50 UTC, disq commented on foundational_security/policy.hcl
> +            query = file("queries/kms/customer_policy_blocked_kms-actions.sql")
Nit:
```suggestion
            query = file("queries/kms/customer_policy_blocked_kms_actions.sql")
```
Rename the file as well

2021-12-03 09:51 UTC, disq commented on queries/kms/rotation_enabled_for_customer_key.sql
> +where rotation_enabled is false
`is false` or `is distinct from true`? (ie. if it's null, then what?)

2021-12-06 15:10 UTC, spangenberg commented on queries/kms/rotation_enabled_for_customer_key.sql
> +where rotation_enabled is false
Actually just reformatted the file, not quite sure.

2021-12-06 15:13 UTC, spangenberg commented on queries/kms/inline_policy_blocked_kms_actions.sql
> +where arn not like '%service-role/%'
Good catch!

2021-12-06 15:42 UTC, disq commented on foundational_security/policy.hcl
> +            query = file("queries/kms/customer_policy_blocked_kms-actions.sql")
marked as resolved but I see it's still typoed

2021-12-06 15:59 UTC, spangenberg commented on foundational_security/policy.hcl
> +            query = file("queries/kms/customer_policy_blocked_kms-actions.sql")
Sorry, didn't push yet just did it locally.

2021-12-06 16:09 UTC, bbernays commented on queries/kms/inline_policy_blocked_kms_actions.sql
> +              'kms:reencryptfrom'] )
At this time there is no way to simplify this query without taking on more complexity in a single use function. Thanks for looking into the issue.

2021-12-06 16:24 UTC, bbernays approved these changes
LGTM

2021-12-06 16:25 UTC, merged